server:
  port: 8088
  # servlet \u4E0A\u4E0B\u6587\u8DEF\u5F84\uFF0C\u9ED8\u8BA4/ ,\u53EF\u4EE5\u901A\u8FC7\u6B64\u65B9\u5F0F\u8BBE\u7F6E\u4E0A\u4E0B\u6587\u8BBF\u95EE\u8DEF\u5F84
  servlet:
    context-path: /im_sys
spring:
  datasource:
    name: im_bird_sys
    #\u91C7\u7528druid\u7684\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    #连接数据库的url
    url: jdbc:mysql:///im_bird
    #驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用户名
    username: root
    password: 810848107
    #监控统计
    filters: stat
    initial-size: 2  #初始化连接
    max-idle: 10 #最大空闲连接
    min-idle: 1  # 最小空闲连接
    max-active: 20  #最大活动链接
    #获取链接超时的等待时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空间连接
    time-between-evict-runs-millis: 60000
    #一个连接在连接池中最小生存空间
    min-evictable-time-millis: 300000
    #验证连接有效与否的sql，不同的数量配置不同
    validation-query: SELECT 'x'
    #指名连接是否被空间连接回收器（如果有）进行检验，如果检测失败，则连接将被从池中去除
    test-while-idle: true
    #借出连接时不要测试，否则影响性能
    test-on-borrow: false
  #
    mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 172.17.9.194:22122